// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzzxsualkfxcqsfqpzgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6enhzdWFsa2Z4Y3FzZnFwemdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjQ3NjUsImV4cCI6MjA2MTc0MDc2NX0.wzXGYMLKNQDGsI9T2UACNmiWSxumGashjMXwUnBeYl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);